"""Profit-focused Grader Council proposals."""

from __future__ import annotations

from collections.abc import Sequence

from .models import FeatureVector, RubricCandidate, RubricVersion


def propose_rubric_candidates(active: RubricVersion, features: Sequence[FeatureVector]) -> tuple[RubricCandidate, ...]:
    """Return bounded rubric variations for Slow Brain to test."""
    positive_profit = sum(feature.net_return_pct for feature in features if feature.sentiment == "positive")
    negative_profit = sum(feature.net_return_pct for feature in features if feature.sentiment == "negative")
    candidates = [
        _candidate(
            active,
            "raise_threshold",
            buy_threshold=active.buy_threshold + 0.07,
            reason="reduce weak BUYs and improve precision",
        ),
        _candidate(
            active,
            "lower_threshold",
            buy_threshold=active.buy_threshold - 0.05,
            reason="capture more missed profitable BUYs",
        ),
        _candidate(
            active,
            "trend_heavier",
            weight_delta={"trend": 0.08, "sentiment": -0.04, "catalyst": -0.04},
            reason="increase trend discipline",
        ),
        _candidate(
            active,
            "catalyst_heavier",
            weight_delta={"catalyst": 0.08, "momentum": -0.04, "volume": -0.04},
            reason="increase catalyst discipline",
        ),
    ]
    if negative_profit < positive_profit:
        candidates.append(
            _candidate(
                active,
                "negative_penalty",
                weight_delta={"sentiment": 0.08, "mean_reversion": -0.04, "volume": -0.04},
                sell_threshold=active.sell_threshold + 0.05,
                reason="penalize negative sentiment when it underperforms positive candidates",
            )
        )
    return tuple(candidates)


def _candidate(
    active: RubricVersion,
    suffix: str,
    *,
    reason: str,
    buy_threshold: float | None = None,
    sell_threshold: float | None = None,
    weight_delta: dict[str, float] | None = None,
) -> RubricCandidate:
    weights = dict(active.weights)
    for key, delta in (weight_delta or {}).items():
        weights[key] = max(0.0, weights.get(key, 0.0) + delta)
    total = sum(weights.values()) or 1.0
    normalized = {key: round(value / total, 4) for key, value in weights.items()}
    rubric = RubricVersion(
        version=f"{active.version}_{suffix}",
        weights=normalized,
        buy_threshold=round(buy_threshold if buy_threshold is not None else active.buy_threshold, 4),
        sell_threshold=round(sell_threshold if sell_threshold is not None else active.sell_threshold, 4),
        max_position_pct=active.max_position_pct,
        notes=(f"Candidate generated by Grader Council: {reason}.",),
    )
    return RubricCandidate(
        candidate_id=f"candidate_{suffix}",
        parent_version=active.version,
        rubric=rubric,
        reason=reason,
    )
