"""Reports generated by TheSlowBrain."""

from __future__ import annotations

import json
from collections.abc import Iterable
from dataclasses import asdict
from pathlib import Path

from .eval_council import CalibrationReport
from .gating_model import GatingModelReport, report_to_dict
from .models import (
    BacktestResult,
    OrderIntent,
    PortfolioState,
    PromotionDecision,
    TelegramCioBrief,
    TradeDecision,
)


def build_eric_brief(decisions: tuple[TradeDecision, ...], portfolio: PortfolioState) -> TelegramCioBrief:
    buys = tuple(_unique(decision.ticker for decision in decisions if decision.action == "BUY"))
    sells = tuple(
        _unique(
            decision.ticker
            for decision in decisions
            if decision.action == "SELL" and decision.ticker in portfolio.holdings
        )
    )
    holdings = portfolio.holdings
    profit = portfolio.profit_since_first_trade_pct
    lines = (
        "Eric - TheSlowBrain",
        f"Stocks to buy are: {_format_items(buys)}",
        f"Stocks to sell are: {_format_items(sells)}",
        f"Current portfolio stocks are: {_format_items(holdings)}",
        f"Profit since first trade as a percentage is: {_format_profit(profit)}",
        "Risk/confidence note: paper/shadow decision only; no live order sent.",
    )
    return TelegramCioBrief(
        stocks_to_buy=buys,
        stocks_to_sell=sells,
        current_portfolio_stocks=holdings,
        profit_since_first_trade_pct=profit,
        lines=lines,
    )


def write_first_report(
    *,
    output_json: Path,
    output_md: Path,
    promotion: PromotionDecision,
    decisions: tuple[TradeDecision, ...],
    portfolio: PortfolioState,
    brief: TelegramCioBrief,
    blocked_order_intents: tuple[OrderIntent, ...] = (),
    import_record_count: int = 0,
    portfolio_backtest: BacktestResult | None = None,
    decision_capture_path: Path | None = None,
    decision_outcome_stream_path: Path | None = None,
    active_rubric_state_path: Path | None = None,
    gating_gate_state_path: Path | None = None,
    track_record_path: Path | None = None,
    outcome_stream_training: dict[str, object] | None = None,
    human_calibration: CalibrationReport | None = None,
    gating_model: GatingModelReport | None = None,
    gating_promotion: dict[str, object] | None = None,
) -> dict[str, object]:
    payload: dict[str, object] = {
        "schema": "theslowbrain.first_report.v1",
        "promotion_decision": asdict(promotion),
        "trade_decisions": [asdict(decision) for decision in decisions],
        "blocked_order_intents": [asdict(intent) for intent in blocked_order_intents],
        "import_record_count": import_record_count,
        "portfolio": asdict(portfolio),
        "portfolio_backtest": asdict(portfolio_backtest) if portfolio_backtest is not None else None,
        "decision_capture_path": str(decision_capture_path) if decision_capture_path is not None else None,
        "decision_outcome_stream_path": (
            str(decision_outcome_stream_path) if decision_outcome_stream_path is not None else None
        ),
        "active_rubric_state_path": str(active_rubric_state_path) if active_rubric_state_path is not None else None,
        "gating_gate_state_path": str(gating_gate_state_path) if gating_gate_state_path is not None else None,
        "track_record_path": str(track_record_path) if track_record_path is not None else None,
        "outcome_stream_training": outcome_stream_training,
        "human_calibration": _human_calibration_payload(human_calibration),
        "gating_model": report_to_dict(gating_model) if gating_model is not None else None,
        "gating_promotion": gating_promotion,
        "eric_brief": asdict(brief),
        "safety": {
            "old_reports_imported": False,
            "broker_live_execution_allowed": False,
        },
    }
    output_json.parent.mkdir(parents=True, exist_ok=True)
    output_json.write_text(json.dumps(payload, indent=2, sort_keys=True), encoding="utf-8")
    output_md.write_text(render_markdown(payload), encoding="utf-8")
    return payload


def render_markdown(payload: dict[str, object]) -> str:
    brief = payload["eric_brief"]
    if not isinstance(brief, dict):
        raise TypeError("eric_brief must be a dict")
    lines = brief.get("lines")
    if not isinstance(lines, (list, tuple)):
        raise TypeError("eric_brief.lines must be a sequence")
    calibration = payload.get("human_calibration")
    calibration_lines: list[str] = []
    if isinstance(calibration, dict):
        calibration_lines = [
            "",
            "## Human Calibration",
            f"- Status: {calibration.get('status')}",
            f"- Examples: {calibration.get('example_count')}",
            f"- Kappa: {calibration.get('kappa')}",
            f"- Caveat: {calibration.get('confidence_note')}",
        ]
    gating = payload.get("gating_model")
    gating_lines: list[str] = []
    if isinstance(gating, dict):
        gating_lines = [
            "",
            "## PR9 Gating Model",
            f"- Status: {gating.get('status')}",
            f"- Selected source: {gating.get('selected_source')}",
            f"- Fallback active: {gating.get('fallback_active')}",
            f"- Reason: {gating.get('fallback_reason')}",
        ]
    state_lines = [
        "",
        "## Learning State",
        f"- Active rubric state: {payload.get('active_rubric_state_path')}",
        f"- Gating gate state: {payload.get('gating_gate_state_path')}",
        f"- Track record: {payload.get('track_record_path')}",
    ]
    rendered = [*(str(line) for line in lines), *calibration_lines, *gating_lines, *state_lines]
    return "# TheSlowBrain First Report\n\n" + "\n".join(rendered) + "\n"


def _human_calibration_payload(report: CalibrationReport | None) -> dict[str, object]:
    if report is None:
        return {
            "status": "not_available",
            "example_count": 0,
            "kappa": None,
            "warnings": ("Held-out human anchor is not available.",),
            "confidence_note": "no anchor labels available",
            "adoption_binding": False,
        }
    low_n = report.example_count <= 30
    note = (
        f"n={report.example_count}, low-confidence; not adoption-binding"
        if low_n
        else f"n={report.example_count}; not adoption-binding until explicitly promoted"
    )
    return {
        "status": report.status,
        "human_examples_required": report.human_examples_required,
        "example_count": report.example_count,
        "kappa": report.kappa,
        "warnings": report.warnings,
        "confidence_note": note,
        "adoption_binding": False,
    }


def _format_items(items: tuple[str, ...]) -> str:
    return ", ".join(items) if items else "none"


def _format_profit(value: float | None) -> str:
    if value is None:
        return "unknown"
    sign = "+" if value >= 0 else ""
    return f"{sign}{value:.2f}%"


def _unique(values: Iterable[str]) -> list[str]:
    seen: set[str] = set()
    result: list[str] = []
    for raw in values:
        value = str(raw).upper()
        if value and value not in seen:
            seen.add(value)
            result.append(value)
    return result
